services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"  # Truy cập frontend qua http://localhost

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - frontend  # (Tùy chọn) Đảm bảo backend khởi động sau frontend
