version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"  # Truy cập frontend qua http://localhost
    networks:
      - app_network
    depends_on:
      - backend  # Đảm bảo backend chạy trước

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network
    env_file:
      - backend/.env  # Load biến môi trường cho backend
networks:
  app_network:
    driver: bridge
